name: release

on:
  release:
    types: [published]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pypi-publish:
    name: Upload release to PyPi
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/elt-dagster-meltano/
    permissions:
      # Required for trusted publishing
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Setup Python 3.11
        uses: actions/setup-python@v6.0.0
        with:
          python-version: 3.11
          architecture: x64
          cache: "pip"
          cache-dependency-path: "poetry.lock"

      - name: Install Poetry
        run: pipx install poetry

      - name: Package project
        run: poetry build

      - name: Publish package distribution to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1.13.0

      # Send a slack notification to the auth alert channel
      # - name: Send Slack Notification
      #   uses: slackapi/slack-github-action@v2.1.1
      #   with:
      #     webhook: ${{ secrets.SLACK_WEBHOOK }}
      #     webhook-type: incoming-webhook
      #     payload: |
      #       {
      #         "text": "Dagster-Meltano Build ${{ steps.gitversion.outputs.assemblySemVer }} ${{ job.status }} <@${{ steps.user.outputs.member-id }}>"
      #       }
      #   if: ${{ always() }}